name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
    build:
        name: Azure Pipeline
        runs-on: windows-2019
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/pknit1988/TestAgileProject
            azure-pipeline-name: 'GitApp-guthubActionPipeline'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
